### ISSUE TITLE
Training failes with ModuleNotFoundError when using train_mn.py

### ISSUE THREAD

**Issue by jo7ueb** [mitmul/chainer-pspnet#5]
Hi, I got following error when I tried to train PSP net with your train_mn.py
How can I train my PSPNet model?

```
root@5e6e3385ca5a:/yendo/oss/chainer-pspnet# python3 train_mn.py --result_dir result configs/cityscapes/pspnet.yml
Warning: using naive communicator because only naive supports CPU-only execution
==========================================
Num process (COMM_WORLD): 1
Using single_node communicator
Chainer version: 3.4.0
ChainerMN version: 1.2.0
cuda: True, cudnn: True
result_dir: result
Traceback (most recent call last):
  File "train_mn.py", line 504, in <module>
    trainer = get_trainer(args)
  File "train_mn.py", line 374, in get_trainer
    model = get_model_from_config(config, comm)
  File "train_mn.py", line 239, in get_model_from_config
    loss.module, loss.name, loss.args, comm)
  File "train_mn.py", line 219, in get_model
    mod = import_module(loss_module)
  File "/root/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'loss'
```

**Comment by praveenkumarchandaliya** [comment]
Similar type error

ModuleNotFoundError: No module named 'training.los s'
